version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
    ignored_updates:
      - match:
          dependency_name: "@storybook/*"
      - match:
          dependency_name: "prismjs"
    commit_message:
      prefix: fix
      prefix_development: chore
      include_scope: true
